class RequestType:
    image = "image"
    audio = "audio"
    document = "document"
    url = "url"
    text = "text"
    image_generate = "image_generate"
    internet = "internet"
    upscale = "upscale"
    remove_background = "remove_background"
    generate_same = "generate_same"
    video = "video"
    animate = "animate"
    change_image = "change_image"
    pdf = "pdf"
    suno = "suno"
    riffusion = "riffusion"
    tts = "tts"
